# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mfe.ma.fullname" . }}-nginx-config
  labels:
    app.kubernetes.io/part-of: orch-ui
    release: {{ .Release.Name }}
data:
  config: |
{{ include "mfe.nginx-config" .Values.nginx | indent 4 }}
