# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mfe.admin.fullname" . }}
  labels:
    app.kubernetes.io/part-of: orch-ui
    app: admin
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/part-of: orch-ui
    app: admin
    release: {{ .Release.Name }}
