name: Automatically update version to -dev

# on:
#   push:
#     branches:
#       - main
#       - release-*

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - feature/auto-dev-version

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Version Update Action
        uses: ./.github/workflows/dev-version-update
