name: Update Versions to -dev

on:
  push:
    branches:
      - main
      - release-*
      - feature/auto-dev-version

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Version Update Action
        uses: open-edge-platform/orch-ci/dev-version-update@action-dev-version-update
