# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
name: E2E Tests Workflow
on:
  workflow_call
env:
  CYPRESS_BASE_URL: "http://localhost:8080"

jobs:
  run-e2e-tests-pipeline:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: "npm"

      - name: Install dependencies
        run: |
          node -v
          npm -v
          npm ci

      - name: Build the test code
        run: npm run tests:build

      # - name: Build production UI with mock server
      #   run: bash tools/build-all-mock.sh

      # - name: Serve the UI
      #   run: npx serve dist -s --no-request-logging -p 8080 &

      # - name: Run EIM tests
      #   run: cd tests; npx cypress run --e2e -s cypress/e2e/eim/eim-smoke.cy.ts --env EN_UUID=398395da-c10e-7c47-9b4f-efb34c0b261e
