# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
name: E2E Tests Workflow
on:
  workflow_call

jobs:
  run-e2e-tests-pipeline:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: "npm"

      - name: Install dependencies
        run: |
          node -v
          npm -v
          npm ci

      - name: Build
        run: npm run tests:build
